version: "3"

services:
  api:
    image: benjaminlandry/swagger_falsy_libs:falsy_libs
    build: ./api
    ports:
      - "8090:8090"
    container_name: api
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    container_name: mongodb3
