mongodb:
  image: mongo:latest
  container_name: mongodb
  ports:
    - "27017:27017"

api:
  build: ./api
  container_name: api
  volumes:
    - .:/usr/src/api_swagger
  environment:
    - MONGODB_HOST=172.17.0.4
    - MONGODB_PORT=27017
  #links:
  #- mongodb
  ports:
    - "8090:8090"