version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  api:
    image: api:latest
    container_name: api
    volumes:
      - .:/usr/src/api_swagger
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    #links:
    #- mongodb
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
