api:
  image: api:latest
  container_name: api
  # volumes:
  #  - .:/usr/src/api_swagger
  environment:
    #- MONGODB_HOST=mongodb
    - MONGODB_HOST=172.17.0.1
    - MONGODB_PORT=27017
  #links:
  #- mongodb
  ports:
    - "8090:8090"
  tty: true
  #command: sh /usr/src/api_swagger/script.sh

